name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: |
            cd lecture
            python3 build.py
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: lecture/main.pdf
